### ISSUE TITLE
How to transform my video to .csv or .arff?

### ISSUE THREAD

**Issue by yy19931029** [vcuculo/AUplayer#1]
Hello, I use your nice work to study facial action unit, I saw your txt in /data/, but I want to make my video to see facial au, I have video but I don't have txt, how to transform video to .csv or .arff to make txt。

**Comment by vcuculo** [comment]
@yy19931029 thanks for your question.
The .csv file is produced by adopting https://github.com/TadasBaltrusaitis/OpenFace 
and running it with:
`FeatureExtraction.exe -f "video.avi" -aus`

this will produce a csv file that you can convert to a .mat with `csvparser.m` included in this repository.

**Comment by yy19931029** [comment]
Thank you!
